MyFirstPull
djo1975/HelloMicroverse pull request #1
Opened 2022-11-29 15:56 UTC by djo1975

2022-11-29 16:11 UTC, christianbiring1 requested changes
Hi @djo1975 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/204580931-07be9c4a-b3ce-423c-b509-e0de2003ac7c.gif)


## Highlights
- [ ] The linters were set up correctly :+1: 
- [ ] The correct README was used :+1: 

## Required Changes ♻️
- [ ] `KINDLY MAKE SURE ALL YOUR LINTERS CHECKS ARE GREEN` :heavy_check_mark: 
Hint: You may consider running the command `npx stylelint "**/*.{css,scss}" --fix` to fix the style linters that are failing.
You may consider checking the entire documentation [here](https://github.com/microverseinc/linters-config/tree/master/html-css)

- [ ] `KINDLY MAKE SURE YOUR PR HAS A DESCRIPTIVE title telling what changes were introduced in the project.`
`Hint: Hello-microverse` would sound better than `MyFirstPull`
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 16:11 UTC, christianbiring1 commented on readme.md
> +
- [ ] Kindly make sure your README has a detailed description telling what the project is about.
`Hint: You may consider taking` [this](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md#:~:text=Estimated%20time%3A%200.5h-,Description,-In%20this%20project) for reference.

2022-11-29 16:11 UTC, christianbiring1 commented on Index.html
> +    <title>Document</title>
- [ ] Kindly make sure your CSS file is linked correctly with your HTML
`Hint: You may consider adding <link rel="stylesheet" href="styles.css">`

2022-11-29 17:21 UTC, djo1975 commented
hi
now I fixed
best regards Mladan

On Tue, Nov 29, 2022 at 5:11 PM Christian Biringanine <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @djo1975 <https://github.com/djo1975> ,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> STATUS: REQUEST CHANGES ♻️
>
> [image: soclose]
> <https://user-images.githubusercontent.com/97100091/204580931-07be9c4a-b3ce-423c-b509-e0de2003ac7c.gif>
> Highlights
>
>    - The linters were set up correctly 👍
>    - The correct README was used 👍
>
> Required Changes ♻️
>
>    -
>
>    KINDLY MAKE SURE ALL YOUR LINTERS CHECKS ARE GREEN ✔️
>    Hint: You may consider running the command npx stylelint
>    "**/*.{css,scss}" --fix to fix the style linters that are failing.
>    You may consider checking the entire documentation here
>    <https://github.com/microverseinc/linters-config/tree/master/html-css>
>    -
>
>    KINDLY MAKE SURE YOUR PR HAS A DESCRIPTIVE title telling what changes
>    were introduced in the project.
>    Hint: Hello-microverse would sound better than MyFirstPull
>    *Check the comments under the review.*
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In readme.md
> <https://github.com/djo1975/HelloMicroverse/pull/1#discussion_r1034948197>
> :
>
> > +
>
> +Is a practice project .
>
> +
>
> +
>
>
>
>    - Kindly make sure your README has a detailed description telling what
>    the project is about.
>    Hint: You may consider taking this
>    <https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md#:~:text=Estimated%20time%3A%200.5h-,Description,-In%20this%20project>
>    for reference.
>
> ------------------------------
>
> In Index.html
> <https://github.com/djo1975/HelloMicroverse/pull/1#discussion_r1034953068>
> :
>
> > +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <title>Document</title>
>
>
>
>    - Kindly make sure your CSS file is linked correctly with your HTML
>    Hint: You may consider adding <link rel="stylesheet" href="styles.css">
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/djo1975/HelloMicroverse/pull/1#pullrequestreview-1197844956>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A33IBUOAGJONF2R3QLWJN3TWKYTMZANCNFSM6AAAAAASOUQQRM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-30 08:28 UTC, RiyaBulia12 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 
Hi @djo1975 👋🏽  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)
## Highlights
* Correct README template ✅ 
* Linters setup correctly 🟢 
* Correct GitHub Flow 👍🏽 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 08:33 UTC, merged